config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'donor/donor_home'
  #get 'request/req'
  get 'admin/dashboard'
 # resources :admin
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    get "/admin_dashboard", to: "admin#dashboard"
    get "donor_registration", to: "donors#new"
       get "blood_stats", to: "admin#blood_av_stats"
    get "/admin_handled_request", to: "admin#admin_handled_request"

    # get "/admin_login", to: "admin#admin_login"
    get "/handle_req/:id", to: "admin#handle_req", as:"handle_req"
   # get "/donor_form", to: "donor#new_donor_form"
  # Defines the root path route ("/")
   root "home#index"
   #root "admin#admin_login"
   #root "sessions#home"
   resources :home,only:[:new,:check]
   get "forgot_password", to:"home#forgot_password",as:"forgot_password"
   post "/search",to:"home#check",as:"search"
   post "/reset_pwd",to:"home#reset_pwd",as:"reset_pwd"
   get "display_msg",to:"home#display_msg",as:"display_msg"
   get "reset_password", to:"home#reset_password",as:"reset_password"

   resources :donors
   resources :admins

   resources :requests
   get 'req_dashboard',to:'dashboard#index',as:'req_dashboard'
   get 'request_new',to:"requests#new",as:"request_new"
    get 'request_list',to:"requests#index",as:"request_list"
  resources :requestors
  resources :sessions,only: [:new,:create, :destory]
  get 'req_signup', to:'requestors#new', as:"req_signup"
  get 'req_login',to:"sessions#new",as:"req_login"

  get 'admin_login',to:"uasessions#new",as:"admin_login"
  # get 'admin_login',to:"sessions#new_admin",as:"admin_login"
  get 'logout',to:"sessions#destroy", as: "logout"
  get 'a_logout',to:"uasessions#destroy", as: "a_logout"

  #U_Admin
  get "sign_in", to: "uasessions#new"
  post "sign_in", to: "uasessions#create"

  get "sign_up", to: "uaregistrations#new"
  post "sign_up", to: "uaregistrations#create"


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_user_logged_in!
  helper_method :home_page?
  def home_page?
      false
  end
  def index
  end

  
end

app/views/dashboard/_header.html.erb
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<%= link_to 'Blood Donation Forum',root_path,class:"navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse " id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ">


 <% if current_requestor %>
   <li class="nav-item">
       <%= link_to "New Request", request_new_path,class:"nav-link" %>


      </li>
      <li class="nav-item">
       <%= link_to "Request Status" , request_list_path,class:"nav-link" %>


      </li>
   <li class="nav-item">
        <%= link_to "Sign Out", logout_path,method: :delete,class:"nav-link" %>

      </li>

<% elsif current_admin %>
<li class="nav-item">
       <%= link_to "Dashboard ", admin_dashboard_path,class:"nav-link" %>


      </li>
         <li class="nav-item">
       <%= link_to "Handled Request", admin_handled_request_path,class:"nav-link" %>


      </li>
    </li>
         <li class="nav-item">
       <%= link_to "Blood stats", blood_stats_path,class:"nav-link" %>


      </li>

       <li class="nav-item">
        <%= link_to "Sign Out", a_logout_path,method: :delete,class:"nav-link" %>

      </li>
      <%#end%>



      <% else %>


    <form class="form-inline  my-lg-0 float-left ">

<div class="input-group mb-2 mr-sm-2">

      <%= link_to 'Requestor Log In', req_login_path  ,class:"btn btn-outline-primary" %>
</div>
<div class="input-group mb-2 mr-sm-2">

      <%= link_to 'Requestor Sign Up', req_signup_path ,class:"btn btn-outline-info" %>
</div>
<div class="input-group mb-2 mr-sm-2">

      <%= link_to 'Donor Registration', donor_registration_path ,class:"btn btn-outline-info" %>
</div>


    </form>
    </ul>
       <% end %>



  </div>
</nav>

app/views/dashboard/index.html.erb
      <br>

<h1>Blood Donation Forum</h1>



    <div class="container">
  <div class="row">
    <div class="col-sm">

    </div>




    <div class="col-mm">

    <% if current_requestor %>
Welcome  : <%= current_requestor.emailId %>

<hr/>
   <div class="card">
  <h5 class="card-header"> <%= image_tag "logo.png", class:"card-img-top" %></h5>
  <div class="card-body">
    <h5 class="card-title">Create a Blood Request </h5>
    <p class="card-text">

     <%= link_to "New Request", request_new_path,class:"btn btn-info" %>
     </p>
      </div>

    </div>


  </div>
 <div class="col-sm">
      <%= link_to "Log out", logout_path ,:class=>"btn btn-primary"%>

    </div>
<% else %>

<% end %>
  <div class="row">
    <div class="col">

  </div>
</div>




    </div>
    <div class="col-sm">
<% if notice %>
      <%= render 'layouts/alert' %>
      <% end %>
    </div>
  </div>
</div>