config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'donor/donor_home'
  #get 'request/req'
  get 'admin/dashboard'
 # resources :admin
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    get "/admin_dashboard", to: "admin#dashboard"
    get "donor_registration", to: "donors#new"
       get "blood_stats", to: "admin#blood_av_stats"
    get "/admin_handled_request", to: "admin#admin_handled_request"

    # get "/admin_login", to: "admin#admin_login"
    get "/handle_req/:id", to: "admin#handle_req", as:"handle_req"
   # get "/donor_form", to: "donor#new_donor_form"
  # Defines the root path route ("/")
   root "home#index"
   #root "admin#admin_login"
   #root "sessions#home"
   resources :home,only:[:new,:check]
   get "forgot_password", to:"home#forgot_password",as:"forgot_password"
   post "/search",to:"home#check",as:"search"
   post "/reset_pwd",to:"home#reset_pwd",as:"reset_pwd"
   get "display_msg",to:"home#display_msg",as:"display_msg"
   get "reset_password", to:"home#reset_password",as:"reset_password"

   resources :donors
   resources :admins

   resources :requests
   get 'req_dashboard',to:'dashboard#index',as:'req_dashboard'
   get 'request_new',to:"requests#new",as:"request_new"
    get 'request_list',to:"requests#index",as:"request_list"
  resources :requestors
  resources :sessions,only: [:new,:create, :destory]
  get 'req_signup', to:'requestors#new', as:"req_signup"
  get 'req_login',to:"sessions#new",as:"req_login"

  get 'admin_login',to:"uasessions#new",as:"admin_login"
  # get 'admin_login',to:"sessions#new_admin",as:"admin_login"
  get 'logout',to:"sessions#destroy", as: "logout"
  get 'a_logout',to:"uasessions#destroy", as: "a_logout"

  #U_Admin
  get "sign_in", to: "uasessions#new"
  post "sign_in", to: "uasessions#create"

  get "sign_up", to: "uaregistrations#new"
  post "sign_up", to: "uaregistrations#create"


end

app/views/admin/_arequest.html.erb
<%#= current_requestor.id%>
<% if request.isConfirmed   %>

  <td>

    <%= request.id %>
  </td>

  <td>

    <%= request.bloodType %>
  </td>

  <td>

    <%= request.location %>
  </td>

  <td>
<% if request.isConfirmed %>
    <%if request.allocationCode ==-404%>
     Declined ❌
    <%else%>
 Allocated ✅
    <%end%>
    <%#= request.isConfirmed %>
    <%else%>
Pending ⏳
    <%end%>
  </td>

  <td>
    <%if request.allocationCode ==-404%>
 Declined ❌

    <%else%>
    <% if request.isConfirmed %>
    Allocation code: <%= request.allocationCode %>, Location: <%= request.allocationCode %>
    <%else%>
    Pending ⏳
    <%end%>
    <%end%>
  </td>
 
<% end %>

app/views/admin/admin_handled_request.html.erb
<p style="color: green"><%= notice %></p>

<h1>Handled Requests</h1>
<input type="text" class="form-control" id="myInput" onkeyup="myFunction()" placeholder="Search" title="Enter search">
<br>
<br>
<table id="myTable" class= "table table-striped table-bordered results">
    <thead class="thead-dark">
    <tr>
      <th scope="col">Request ID</th>
      <th scope="col">Requestor ID</th>
      <th scope="col">Blood Group</th>
      <th scope="col">Location</th>
      <th scope="col">Is Handled?</th>
      <th scope="col">Allocation code</th>
      <th scope="col">Location Allocated</th>
    </tr>
  </thead>
  <tbody>
  <% @requests.each do |request| %>
  <tr>
   
    

<% if request.isConfirmed   %>

  <td>

    <%= request.id %>
  </td>
  <td>

    <%= request.requestorID %>
  </td>

  <td>

    <%= request.bloodType %>
  </td>

  <td>

    <%= request.location %>
  </td>

  <td>
<% if request.isConfirmed %>
    <%if request.allocationCode ==-404%>
     Declined ❌
    <%else%>
 Allocated ✅
    <%end%>
    <%#= request.isConfirmed %>
    <%else%>
Pending ⏳
    <%end%>
  </td>

  <td>
    <%if request.allocationCode ==-404%>
 Declined ❌

    <%else%>
    <% if request.isConfirmed %>
    <%= request.allocationCode %> 
    <%else%>
    Pending ⏳
    <%end%>
    <%end%>
  </td>

 
<% end %>


   <% if request.isConfirmed %>
    <%if request.allocationCode ==-404%>
     <td>
     Declined ❌
      </td>
      </tr>
    <%else%>
      <td>
<%=request.locationAllocated %>
  </td>
</tr>
    <%end%>

    <%#= request.isConfirmed %>
    <%else%>

    <%end%>
  </#td>

    

  <% end %>
  </tbody>
</table>

<%#= link_to "New request", new_request_path %>

app/views/admin/admin_login.html.erb
<%="admin"%>

app/views/admin/blood_av_stats.html.erb
<h1>Available blood stats</h1>
<%= pie_chart @data ,  width: "800px", download: true,  library: {backgroundColor: "#DAF7A6"}%>
<br>
<button type="button"   id="hideMe" class="btn btn-primary" onclick="window.print()">

Print stats</button>
<%#= @data %>

app/views/admin/dashboard.html.erb
<nav class="navbar bg-light">
  <div class="container-fluid">
    <a class="navbar-brand"><h4 style="color:  darkorchid; "> <%= image_tag 'img_dashboard.png', size:"30" %>    Admin Dashboard</h4></a>

  </div>
</nav>

<table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Request ID</th>
        <th>Blood Group</th>
        <th>Location</th>
        <th>Action</th>

      </tr>
    </thead>

    <tbody>
      <%if @allocation_here %>
        <% if @donor_id_allo == -404%>
      <div class="alert alert-danger" role="alert">

         Last Request was Declined: RequestID <%= @request_allo.id %> of <%= @request_allo.bloodType %>
       on <%= @last_allocation %>

<%else%>
      <div class="alert alert-info" role="alert">
Last Request was Accepted: <%=@donor_allo.id%> to <%= @request_allo.id %> of <%= @request_allo.bloodType %>
       <%= @last_allocation %>

 <%end%>
</div>


          <%end%>
      <% @requests.each do |request| %>
           <% if request.isConfirmed==false%>
             <tr>

          <td> <%= request.id %></td>
          <td> <%= request.bloodType %></td>
          <td><%= request.location %></td>


          <td>
            <%@req_id=request.id%>

  <%= link_to "Handle Request", handle_req_path(@req_id), class:"btn btn-primary" %>

          </td>
        </tr>
    <%end%>
      <% end %>
    </tbody>
  </table>

app/views/admin/error_pg.html.erb
 </br>
   <h1 style="color:  darkorchid; text-align: center;">Not Found</h1>
 <h5 style="color:  darkorchid ; text-align: center;">Looks like you are lost, Aren't we all?</h5>

 </br>
 <center>
   <%= image_tag 'img_404.png', size:"300" %>
  </center>

app/views/admin/handle_req.html.erb
<nav class="navbar bg-light">
  <div class="container-fluid">
    <a class="navbar-brand"><h4 style="color:  darkorchid; "> <%= image_tag 'img_handle_req.png', size:"30" %>    Handle Request</h4></a>

  </div>
</nav>


<table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Request ID</th>
        <th>Blood Group</th>
        <th>Location</th>

      </tr>
    </thead>

    <tbody>
      <tr>
        <td> <%= @request.id %> 
<%#=id:"%>
<%temp_req_mail= Requestor.find(@request.requestorID).emailId %>
<%#= temp_req_mail %>
         </td>

        <td> <%= @request.bloodType %></td>

        <td> <%= @request.location %></td>

      </tr>
    </tbody>
  </table>

<% if @donors.empty? %>
 <%= link_to "Delete",  admin_dashboard_path(:did=> -404,:rid=>@request.id ),  class:"btn btn-danger"  %>
   <h4 style="color:  darkorchid; text-align: center;">No Matching Donors for this Request</h4>


 </br>
 <center>

  <%= image_tag 'img_warning.png', size:"300" %>
  </center>

<%else%>
<div>
<center><h6>Donors</h6></center>
<table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>donorID</th>
        <th>Blood Group</th>
        <th>Location</th>
        <th>action</th>

      </tr>
    </thead>

    <tbody>
      <% @donors.each do |donor| %>
           <% if donor.isUsed==false%>
             <tr>

          <td> <%= donor.id %></td>
          <td> <%= donor.bloodGroup %></td>
          <td><%= donor.location %></td>

          <td> <% req_id= @request.id %><%= link_to "Allocate",  admin_dashboard_path(:did=> donor.id,:rid=>req_id ),  class:"btn btn-success"  %>
          </td>
        </tr>
    <%end%>
      <% end %>
      <% end %>
    </tbody>
  </table>

 