config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'donor/donor_home'
  #get 'request/req'
  get 'admin/dashboard'
 # resources :admin
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    get "/admin_dashboard", to: "admin#dashboard"
    get "donor_registration", to: "donors#new"
       get "blood_stats", to: "admin#blood_av_stats"
    get "/admin_handled_request", to: "admin#admin_handled_request"

    # get "/admin_login", to: "admin#admin_login"
    get "/handle_req/:id", to: "admin#handle_req", as:"handle_req"
   # get "/donor_form", to: "donor#new_donor_form"
  # Defines the root path route ("/")
   root "home#index"
   #root "admin#admin_login"
   #root "sessions#home"
   resources :home,only:[:new,:check]
   get "forgot_password", to:"home#forgot_password",as:"forgot_password"
   post "/search",to:"home#check",as:"search"
   post "/reset_pwd",to:"home#reset_pwd",as:"reset_pwd"
   get "display_msg",to:"home#display_msg",as:"display_msg"
   get "reset_password", to:"home#reset_password",as:"reset_password"

   resources :donors
   resources :admins

   resources :requests
   get 'req_dashboard',to:'dashboard#index',as:'req_dashboard'
   get 'request_new',to:"requests#new",as:"request_new"
    get 'request_list',to:"requests#index",as:"request_list"
  resources :requestors
  resources :sessions,only: [:new,:create, :destory]
  get 'req_signup', to:'requestors#new', as:"req_signup"
  get 'req_login',to:"sessions#new",as:"req_login"

  get 'admin_login',to:"uasessions#new",as:"admin_login"
  # get 'admin_login',to:"sessions#new_admin",as:"admin_login"
  get 'logout',to:"sessions#destroy", as: "logout"
  get 'a_logout',to:"uasessions#destroy", as: "a_logout"

  #U_Admin
  get "sign_in", to: "uasessions#new"
  post "sign_in", to: "uasessions#create"

  get "sign_up", to: "uaregistrations#new"
  post "sign_up", to: "uaregistrations#create"


end

app/controllers/home_controller.rb
require 'bcrypt'
class HomeController < ApplicationController
  
  helper_method :home_page?
  def home_page?
      true
  end
  def index
  end

  def new
  end
  def forgot_password

  end
  def display_msg
p params[:emailid]
p params[:token]
  end
  def check
    requestor=Requestor.find_by_emailId(params[:emailId])
    @token=random_token
    if requestor
      
      #redirect_to  home_index_path,notice: "Reset Password linked mailed to your registered email id "+@token
      if requestor.update_column(:pwdtoken,@token)
      redirect_to  display_msg_path(:emailId=>params[:emailId],:token=>@token),notice: "Reset Password linked mailed to your registered email id "
      else 
        redirect_to  home_index_path,notice: params[:emailId]+" The error update password token."
      end
    else
      redirect_to  home_index_path,notice: params[:emailId]+" The error user ID does not exist."
  end
end



    def reset_pwd
      requestor=Requestor.find_by_emailId(params[:emailId])
     p "Email id in reset "+params[:emailId]
     p "Token in reset : "+params[:pwdtoken]
      if requestor && requestor.pwdtoken == params[:pwdtoken]
        #redirect_to  home_index_path,notice: "Reset Password linked mailed to your registered email id "+@token
        p requestor.pwdtoken
        my_password = BCrypt::Password.create(params[:password])
        p "Password hash : "+my_password
        if requestor.update_columns(password_digest:my_password,pwdtoken:nil)
          
        redirect_to  home_index_path,notice: "Reset Password of "+params[:emailId]+" is successfull"
        else 
          redirect_to  home_index_path,notice: params[:emailId]+" The error update password ."
        end
      else
        redirect_to  home_index_path,notice: params[:emailId]+" Error : User doest not exist or token mismatch"
      end
      #flash.now[:alert]="Email or Password is invalid"
      #render ""
    end
    def random_token(size=64)
      #(0...64).map{('a'...'z').to_a[rand(26)]}.join
      charset =%w{ A B C D E F G H I J K L  M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z 0 1 2 3 4 5 6 7 8 9 # * $ _ + }
      (0...size).map{ charset.to_a[rand(charset.size)] }.join
    end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_homemenu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
 <%= link_to 'Blood Donation Forum',root_path,class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
   <li class="nav-item">



      </li>
      </ul>
      </div>
    <form class="form-inline my-2 my-lg-0 float-left">


      <%= link_to 'Requestor', req_login_path  ,class:"btn btn-outline-success my-2 my-sm-0 mr-1" %>

      <%= link_to 'Donor', new_donor_path,class:"btn btn-outline-danger my-2 my-sm-0" %>
    </form>
  </div>
</nav>

app/views/home/display_msg.html.erb
<div class="mt-5">

<% if params[:emailId] %>


<div class="card" style="width: 25rem;">
  <div class="card-body">
    <h5 class="card-title">Reset your Blood Requestor password</h5>
    <h6 class="card-subtitle mb-2 text-muted">Blood Forum password reset</h6>
    <p class="card-text">
<h3>Blood Forum password reset</h3>
 
We heard that you lost your Blood Forum password. Sorry about that!

But don’t worry! You can use the following button to reset your password:
<%= link_to 'Reset Password', reset_password_path(:emailId=>params[:emailId],:token=>params[:token])  ,class:"btn btn-success my-2 my-sm-0 mr-1" %></p>
    
    <p>If you don’t use this link within 3 hours, it will expire.</p>
    Thanks,<br>
The Blood Forum Team <br>
    
  </div>
</div>


<% else %>


<% end %>
</div>

app/views/home/forgot_password.html.erb
<div class="row " >
    <div class="col-sm">
      
    </div>
    <div class="col-sm">
      <div class="card mt-5" style="width: 20rem;">
 
   <%= image_tag "logo.png", class:"card-img-top" %>
  <h5 class="card-header">Requestor : Forgot Password</h5>
  <div class="card-body">
    
    <p class="card-text">
    <%= form_with url: "/search", method: :post do |form| %>
<div class="form-group">
<%= label_tag :email_id %>
<%= email_field_tag :emailId,"",class:"form-control"%> 
</div>
<%= hidden_field_tag :forgot_pwd, 1 ,class:"form-control" %>
 
<div class="form-group">

<%= submit_tag "Forgot Password" ,class:" btn btn-primary"  %>
</div>
<% end %>
</p>
  </div>
   </div>
    </div>
    </div>

app/views/home/index.html.erb
      <div class="p-5 mb-4 bg-light rounded-3"  style="margin-top:10px">
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
    <%= image_tag "poster_bd.jpg", class:"d-block w-100" %>
      </div>
    <div class="carousel-item">
       <%= image_tag "5871872.jpg", class:"d-block w-100 " %>
    </div>
    <div class="carousel-item">
       <%= image_tag "Blood-Donor.jpg", class:"d-block w-100" %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
      </div>

  <div class="row">
       <div class="col-lg">


       </div>


  </div>






  <div class="row">
    <div class="col">

  </div>
</div>




    </div>
    <div class="col-sm">
<% if notice %>
      <%= render 'layouts/alert' %>
      <% end %>
    </div>
  </div>
</div>

app/views/home/reset_password.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-sm">
    </div>
    <div class="col-mm">
      <div class="card">
  <h5 class="card-header"> <%= image_tag "logo.png", class:"card-img-top" %></h5>
  <div class="card-body">
    <h5 class="card-title">Reset Password : Requestor</h5>
    <p class="card-text">
  <%= form_with url: "/reset_pwd", method: :post do |form| %>



  <div class="row">
    <div class="col">
      <div class="form-group">
     <%= form.label :email_id, style: "display: block" %>
    <%= form.email_field :emailId, class:"form-control" , Placeholder:"Email Id" ,value:params[:emailId], :disabled => true %>

  </div>
    </div>

    <%= form.hidden_field :pwdtoken ,value: params[:token]%>

      <div class="col">
      <div class="form-group">
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password ,class:"form-control" , Placeholder:"Password" %>
  </div>
    </div>
      <div class="col">
      <div class="form-group">
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation ,class:"form-control" , Placeholder:"password" %>
  </div>
    </div>
    </div>



  <div class="form-group">
    <%= form.submit nil ,:class=>"btn btn-primary" %>
  </div>
<% end %>


    </p>

  </div>
</div>




    </div>
    <div class="col-sm">

    </div>
  </div>
</div>