config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'donor/donor_home'
  #get 'request/req'
  get 'admin/dashboard'
 # resources :admin
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    get "/admin_dashboard", to: "admin#dashboard"
    get "donor_registration", to: "donors#new"
       get "blood_stats", to: "admin#blood_av_stats"
    get "/admin_handled_request", to: "admin#admin_handled_request"

    # get "/admin_login", to: "admin#admin_login"
    get "/handle_req/:id", to: "admin#handle_req", as:"handle_req"
   # get "/donor_form", to: "donor#new_donor_form"
  # Defines the root path route ("/")
   root "home#index"
   #root "admin#admin_login"
   #root "sessions#home"
   resources :home,only:[:new,:check]
   get "forgot_password", to:"home#forgot_password",as:"forgot_password"
   post "/search",to:"home#check",as:"search"
   post "/reset_pwd",to:"home#reset_pwd",as:"reset_pwd"
   get "display_msg",to:"home#display_msg",as:"display_msg"
   get "reset_password", to:"home#reset_password",as:"reset_password"

   resources :donors
   resources :admins

   resources :requests
   get 'req_dashboard',to:'dashboard#index',as:'req_dashboard'
   get 'request_new',to:"requests#new",as:"request_new"
    get 'request_list',to:"requests#index",as:"request_list"
  resources :requestors
  resources :sessions,only: [:new,:create, :destory]
  get 'req_signup', to:'requestors#new', as:"req_signup"
  get 'req_login',to:"sessions#new",as:"req_login"

  get 'admin_login',to:"uasessions#new",as:"admin_login"
  # get 'admin_login',to:"sessions#new_admin",as:"admin_login"
  get 'logout',to:"sessions#destroy", as: "logout"
  get 'a_logout',to:"uasessions#destroy", as: "a_logout"

  #U_Admin
  get "sign_in", to: "uasessions#new"
  post "sign_in", to: "uasessions#create"

  get "sign_up", to: "uaregistrations#new"
  post "sign_up", to: "uaregistrations#create"


end

app/models/requestor.rb
class Requestor < ApplicationRecord

  has_secure_password
  validates :emailId, presence: true, uniqueness: true
  validates_length_of :password, minimum: 6

end

app/controllers/requestors_controller.rb
class RequestorsController < ApplicationController
  #before_action :set_requestor, only: %i[ show edit update destroy ],:require_user_logged_in!

  # GET /requestors or /requestors.json
  #helper_method :home_page?
  #def home_page?
  #  false
#end
  def index
    @requestors = Requestor.all
  end

  # GET /requestors/1 or /requestors/1.json
  def show
  end

  # GET /requestors/new
  def new
    @requestor = Requestor.new
  end

  # GET /requestors/1/edit
  def edit
  end

  # POST /requestors or /requestors.json
  def create
    @requestor = Requestor.new(requestor_params)

    respond_to do |format|
      if @requestor.save
       # format.html { redirect_to requestor_url(@requestor), notice: "Requestor was successfully created." }
       format.html { redirect_to root_url, notice: "Requestor was successfully created." }
        format.json { render :show, status: :created, location: @requestor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @requestor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requestors/1 or /requestors/1.json
  def update
    respond_to do |format|
      if @requestor.update(requestor_params)
        format.html { redirect_to requestor_url(@requestor), notice: "Requestor was successfully updated." }
        format.json { render :show, status: :ok, location: @requestor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @requestor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requestors/1 or /requestors/1.json
  def destroy
    @requestor.destroy

    respond_to do |format|
      format.html { redirect_to requestors_url, notice: "Requestor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_requestor
      @requestor = Requestor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def requestor_params
      params.require(:requestor).permit(:emailId, :password, :password_confirmation, :requestIds)
    end
end

app/views/requestors/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm">
    </div>
    <div class="col-mm">
      <div class="card">
  <h5 class="card-header"> <%= image_tag "logo.png", class:"card-img-top" %></h5>
  <div class="card-body">
    <h5 class="card-title">Sign Up : Requestor</h5>
    <p class="card-text">
    <%= form_with(model: requestor) do |form| %>
  <% if requestor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(requestor.errors.count, "error") %> prohibited this requestor from being saved:</h2>

      <ul>
        <% requestor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row">
    <div class="col">
      <div class="form-group">
    <%= form.label :email_id, style: "display: block" %>
    <%= form.email_field :emailId ,class:"form-control" , Placeholder:"Email Id" %>
  </div>
    </div>
      <div class="col">
      <div class="form-group">
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password ,class:"form-control" , Placeholder:"Password" %>
  </div>
    </div>
      <div class="col">
      <div class="form-group">
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation ,class:"form-control" , Placeholder:"password" %>
  </div>
    </div>
    </div>
<div style="visibility: hidden">
    <%= form.label :requestIds, style: "display: block" %>
    <%= form.text_field :requestIds %>
  </div>
<%= form.hidden_field :isAdmin, value: false %>

  <div class="form-group">
    <%= form.submit nil ,:class=>"btn btn-primary" %>
  </div>
<% end %>


    </p>

  </div>
</div>




    </div>
    <div class="col-sm">

    </div>
  </div>
</div>

app/views/requestors/_requestor.html.erb
<div id="<%= dom_id requestor %>">
  <p>
    <strong>Emailid:</strong>
    <%= requestor.emailId %>
  </p>

  <p>
    <strong>Requestids:</strong>
    <%= requestor.requestIds %>
  </p>

</div>

app/views/requestors/edit.html.erb
<h1>Editing requestor</h1>

<%= render "form", requestor: @requestor %>

<br>

<div>
  <%#= link_to "Show this requestor", @requestor %> |
  <%= link_to "Back to requestors", requestors_path %>
</div>

app/views/requestors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Requestors</h1>

<div id="requestors">
  <% @requestors.each do |requestor| %>
    <%= render requestor %>
    <p>
      <%= link_to "Show this requestor", requestor %>
    </p>
  <% end %>
</div>

<%#= link_to "New requestor", new_requestor_path %>

app/views/requestors/new.html.erb
<h1>New requestor</h1>

<%= render "form", requestor: @requestor %>

<br>

<div>

  <%= link_to "Back to Dashboard", req_dashboard_path %>
</div>

app/views/requestors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @requestor %>

<div>
  <%= link_to "Edit this requestor", edit_requestor_path(@requestor) %> |
  <%= link_to "Back to requestors", requestors_path %>

  <%= button_to "Destroy this requestor", @requestor, method: :delete %>
</div>